### ISSUE TITLE
Saving a Table Lookup Transformer in a PMML file

### ISSUE THREAD

**Issue by pmontu33** [jpmml/sklearn2pmml#70]
I wish to save a custom transformer defined:

```Python
class LookupTransformer(TransformerMixin):

    def __init__(self, lookupfile, default_value=0.):
        self.dict = defaultdict(
            lambda: default_value,
            pd.read_csv(lookupfile).set_index('A').to_dict()['B']
        )

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return np.array(X.apply(lambda x: self.dict[x]))
```

Is it currently possible to do this?

**Comment by vruusmann** [comment]
I would like to reorganize your transformer class to make it more generic. Specifically, I want to move the initialization of the "base dict" object outside of this transformer class.
```Python
class LookupTransformer(TransformerMixin):

  def __init__(self, base_dict, default_value = 0.0):
    self.base_dict = base_dict
    self.default_value = default_value

  def fit(self, X, y = None):
    return self

  def transform(self, X):
    transform_dict = defaultdict(lambda: self.default_value)
    transform_dict.update(self.base_dict)
    return np.array(X.apply(lambda x: transform_dict[x]))
```

You could then construct an instance of `LookupTransformer` based on a CSV file in local filesystem like this:
```Python
base_dict = pandas.read_csv(lookupfile).set_index('key').to_dict()['value']
lookup = LookupTransformer(base_dict)
```

Alternatively, you could define the key-value mapping manually:
```Python
base_dict = {"red" : "no", "yellow" : "no", "green" : "yes"}
lookup = LookupTransformer(base_dict, "no")
```

**Comment by vruusmann** [comment]
What will be the most common key and value data types?
- `int` --> `int`
- `float` --> `float` or `int`
- `str` --> `str`, `float` or `int`

The lookup transformer should be able to handle all those scenarios. For example, it might be needed to collapse or expand the levels of categorical (string-) features before applying the `LabelBinarizer` transformation to them:
```
mapper = DataFrameMapper([
  ("color", [CategoricalDomain(), LookupTransformer(color_base_dict, "black"), LabelBinarizer()])
])
```

**Comment by vruusmann** [comment]
Cross-linking with an earlier related issue: https://github.com/jpmml/sklearn2pmml/issues/14

Looks like there should be two lookup transformers:
1. class `LookupTransformer` - implements "one key to one value"-style mapping. Will be based on the `dict` data structure.
2. class `MultiLookupTransformer` - implements many "multiple keys to one value"-style mapping. Will be based on what? How can one do multi-key lookup in Python?

**Comment by pmontu33** [comment]
Thanks for the quick reply.

More specifically, we are interested in:

* One mapping that's int -> (float, float) with a dictionary with several entries (33k, file size is abt 1 Mbyte)

* One mapping that's string -> float (200 entries, 5 Kbytes)

We would like to minimize space and hopefully O(1) lookup.

1) Would it be possible to store the table outside the class in case the file is too large?
2) Will the lookup work as a hash table?

**Comment by vruusmann** [comment]
> One mapping that's int -> (float, float)

The output of the lookup transform have to be one-dimensional (ie. scalar). So, instead of a single lookup operation that returns a two-value tuple, you would need to have two lookup operations that return a single value each.

>  1. Would it be possible to store the table outside the class in case the file is very large or in case it changes?

I don't think that the size of the `base_dict` argument (to the constructor of `LookupTransformer` dictionary) affects the save in pickle data format (and the subsequent conversion to PMML) in any way. 

But we will know for sure when we have the first prototype ready.

> 2. We would like to minimize space and hopefully O(1) lookup.

The JPMML-Evaluator library implements O(1) lookup, so 33k row table won't be a problem.

**Comment by vruusmann** [comment]
BTW: I'm back at home, and I hope to have the first version of the `LookupTransformer` (both Python and Java sides) published by Monday, 11th of December.

You will receive a GitHub notification when I mark this issue as "fixed" in a commit message.

**Comment by vruusmann** [comment]
I've just published `sklearn2pmml` package version 0.27.0, which introduces the `sklearn2pmml.preprocessing.LookupTransformer` transformation type:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/preprocessing/__init__.py#L19-L38

Example usage:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L243-L260

**Comment by pmontu33** [comment]
Villu,

Many thanks for your quick response.

PM

**Comment by pmontu33** [comment]
Hello,

I recently tested the python part of the code and it works well. However, I am still unable to store the pipeline as a pmml file. I tried outputting a pkl.z file and converting it to pmml with the jar that you provide. I also tried to use skelarn2pmml directly. In both cases I obtain this error message:

SEVERE: Failed to convert
java.lang.IllegalArgumentException: expected one element but was: <class java.lang.Double, class java.lang.Integer>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:322)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:294)
	at sklearn.TypeUtil.getDataType(TypeUtil.java:54)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:114)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:82)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:128)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)

Exception in thread "main" java.lang.IllegalArgumentException: expected one element but was: <class java.lang.Double, class java.lang.Integer>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:322)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:294)
	at sklearn.TypeUtil.getDataType(TypeUtil.java:54)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:114)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:82)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:128)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)

Is this because there is no java support yet?

PS:

```
Here is the code that I used to generate the pipeline:

column = []
target = []

for i in range(30):
    [...]
df = pd.DataFrame({"column": column, "target": target})

mapper = DataFrameMapper([
    ('column', LookupTransformer({"a": 1, "b": 2, "c": 3}, 0.))
], df_out=True)

pl = PMMLPipeline([
    ('mapper', mapper),
    ('regressor', LinearRegression())
])

pl.fit(df, df['target'])
sklearn2pmml(pl, "./pl.pmml", with_repr = True)
```

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: expected one element but was: <class java.lang.Double, class java.lang.Integer>
>	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:322)
>	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:294)
>	at sklearn.TypeUtil.getDataType(TypeUtil.java:54)

The Java side throws an exception, because it cannot determine what is the intended output data type of your `LookupTransformer` step - you are using `int` data type for dictionary values, but `float` data type for the default value.

To avoid this exception, you need to use the same data type for both.

Promoting dictionary values from `int` to `float` (pay attention to the added decimal separator `.`):
```Python
LookupTransformer({"a": 1., "b": 2., "c": 3.}, 0.)
```

Demoting the default value from `float` to `int` (pay attention to the removed decimal separator `.`):
```Python
LookupTransformer({"a": 1, "b": 2, "c": 3}, 0)
```
